### ISSUE TITLE
Make biscuitsec site available on biscuitsec.org

### ISSUE THREAD

**Issue by Frederik-Baetens** [biscuit-auth/website#26]
Currently, https://biscuitsec.org goes nowhere. Conventionally people either redirect www.example.com to example.com, host their site on both domains, or redirect example.com to www.example.com. I guess any of these would be fine, but currently the link in your readme leads to a non-existent website.

**Comment by Geal** [comment]
right, I thought I had set up the redirection already, I must have messed up the configuration

**Comment by Geal** [comment]
this is fixed now
