### ISSUE TITLE
expand the revocation article

### ISSUE THREAD

**Issue by Geal** [biscuit-auth/website#45]
While Biscuit does not specify how revocation information is propagated through a system, we should provide good advice there, because it is a complex part of the authorization system

**Comment by divarvel** [comment]
Yeah, I was confronted with the same issue in https://tech.fretlink.com/so-you-want-to-revoke-macaroons/

Here's what I put there:

> Start simple. If you don't have a lot of services, a static revocation list read at startup (from a file, or an environment variable) can be more than enough. Then you can think about out-of-band polling, or even push notifications. Try to keep things simple, you don't want too many moving parts. Just keep in mind that if you end up calling a central revocation service every time you're checking a token, you might be better off with a centralized session.

The ideas I wanted to put forward:

- Provide a way to set revoked IDs from day one, even if it's a simple one (eg env vars). It's better than nothing and it will allow you to react quickly the first time;
- Avoid reintroducing a SPOF by having a revocation server called everytime a token is validated

For more complex setups maybe there are write-ups we can put as further reading?

**Comment by divarvel** [comment]
I think we could also add something about TTLs and revocation lists being _complementary_: TTLs don't replace a revocation list, but they help keeping it short.
