### ISSUE TITLE
Update node documentation with better examples

### ISSUE THREAD

**Issue by gssakash** [biscuit-auth/website#63]
The documentation for NodeJS could use better examples and I've noticed that the ``index.js`` file in the frontend part of [this](https://github.com/biscuit-auth/biscuit-wasm/tree/main/examples/frontend) repo would be a great replacement to the existing documentation of [NodeJS](https://www.biscuitsec.org/docs/Usage/node/) on the website.

**Comment by divarvel** [comment]
`biscuit-wasm` should be released as a stable version very soon. once it's done, we can indeed port the node example to the website documentation.

**Comment by divarvel** [comment]
handled in #88
